# Site settings
author: Aglae Verduzco
title: Fun-coding
header-img: img/home-bg.png
email: aglae.cv@gmail.com
copyright_name: Aglae Verduzco
description: > # this means to ignore newlines until "baseurl:"
  newtocoding
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Aglaevdz

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
